# Atlantic Storms
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Josephine /mnt/e/MET499/Sick/Josephine
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Kyle /mnt/e/MET499/Sick/Kyle
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Marco /mnt/e/MET499/Sick/Marco
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Omar /mnt/e/MET499/Sick/Omar
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Nana /mnt/e/MET499/Sick/Nana
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Paulette /mnt/e/MET499/Sick/Paulette
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Rene /mnt/e/MET499/Sick/Rene
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Sally /mnt/e/MET499/Sick/Sally
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Teddy /mnt/e/MET499/Sick/Teddy
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Vicky /mnt/e/MET499/Sick/Vicky
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Beta /mnt/e/MET499/Sick/Beta
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Wilfred /mnt/e/MET499/Sick/Wilfred
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Gamma /mnt/e/MET499/Sick/Gamma
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Delta /mnt/e/MET499/Sick/Delta
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Epsilon /mnt/e/MET499/Sick/Epsilon
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Zeta /mnt/e/MET499/Sick/Zeta
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Eta /mnt/e/MET499/Sick/Eta
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Theta /mnt/e/MET499/Sick/Theta
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Iota /mnt/e/MET499/Sick/Iota
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Ana /mnt/e/MET499/Sick/Ana
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Bill /mnt/e/MET499/Sick/Bill
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Claudette /mnt/e/MET499/Sick/Claudette
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Danny /mnt/e/MET499/Sick/Danny
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Elsa /mnt/e/MET499/Sick/Elsa
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Fred /mnt/e/MET499/Sick/Fred
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Grace /mnt/e/MET499/Sick/Grace
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Henri /mnt/e/MET499/Sick/Henri
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Ida /mnt/e/MET499/Sick/Ida
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Kate /mnt/e/MET499/Sick/Kate
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Julian /mnt/e/MET499/Sick/Julian
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Larry /mnt/e/MET499/Sick/Larry
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Mindy /mnt/e/MET499/Sick/Mindy
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Nicholas /mnt/e/MET499/Sick/Nicholas
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Peter /mnt/e/MET499/Sick/Peter
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Rose /mnt/e/MET499/Sick/Rose
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Sam /mnt/e/MET499/Sick/Sam
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Victor /mnt/e/MET499/Sick/Victor
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Wanda /mnt/e/MET499/Sick/Wanda
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Alex /mnt/e/MET499/Sick/Alex
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Bonnie /mnt/e/MET499/Sick/Bonnie
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Colin /mnt/e/MET499/Sick/Colin
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Danielle /mnt/e/MET499/Sick/Danielle
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Earl /mnt/e/MET499/Sick/Earl
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Fiona /mnt/e/MET499/Sick/Fiona
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Gaston /mnt/e/MET499/Sick/Gaston
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Ian /mnt/e/MET499/Sick/Ian
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Julia /mnt/e/MET499/Sick/Julia
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Karl /mnt/e/MET499/Sick/Karl
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Lisa /mnt/e/MET499/Sick/Lisa
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Martin /mnt/e/MET499/Sick/Martin
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Nicole /mnt/e/MET499/Sick/Nicole
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Bret /mnt/e/MET499/Sick/Bret
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Cindy /mnt/e/MET499/Sick/Cindy
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Don /mnt/e/MET499/Sick/Don
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Gert /mnt/e/MET499/Sick/Gert
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Emily /mnt/e/MET499/Sick/Emily
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Franklin /mnt/e/MET499/Sick/Franklin
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Harold /mnt/e/MET499/Sick/Harold
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Idalia /mnt/e/MET499/Sick/Idalia
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Jose /mnt/e/MET499/Sick/Jose
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Katia /mnt/e/MET499/Sick/Katia
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Lee /mnt/e/MET499/Sick/Lee
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Ophelia /mnt/e/MET499/Sick/Ophelia
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Margot /mnt/e/MET499/Sick/Margot
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Nigel /mnt/e/MET499/Sick/Nigel
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Philippe /mnt/e/MET499/Sick/Philippe
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Rina /mnt/e/MET499/Sick/Rina
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Sean /mnt/e/MET499/Sick/Sean
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Tammy /mnt/e/MET499/Sick/Tammy
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Alberto /mnt/e/MET499/Sick/Alberto
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Beryl /mnt/e/MET499/Sick/Beryl
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Chris /mnt/e/MET499/Sick/Chris
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Debby /mnt/e/MET499/Sick/Debby
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Ernesto /mnt/e/MET499/Sick/Ernesto
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Francine /mnt/e/MET499/Sick/Francine
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Gordon /mnt/e/MET499/Sick/Gordon
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Helene /mnt/e/MET499/Sick/Helene
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Isaac /mnt/e/MET499/Sick/Isaac
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Joyce /mnt/e/MET499/Sick/Joyce
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Kirk /mnt/e/MET499/Sick/Kirk
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Leslie /mnt/e/MET499/Sick/Leslie
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Milton /mnt/e/MET499/Sick/Milton
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Nadine /mnt/e/MET499/Sick/Nadine
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Oscar /mnt/e/MET499/Sick/Oscar
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Patty /mnt/e/MET499/Sick/Patty
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Rafael /mnt/e/MET499/Sick/Rafael
# python3 File_DEV.py /mnt/e/Storm_Database.xlsx Sara /mnt/e/MET499/Sick/Sara


# WPAC Storms
# python3 File_DEV_AHI.py /mnt/e/MET499/WPAC_besttrack_combined.xlsx ONE /mnt/e/MET499/WPAC/2019/One
# python3 File_DEV_AHI.py /mnt/e/MET499/WPAC_besttrack_combined.xlsx FOUR /mnt/e/MET499/WPAC/2019/Four